baseURL = "https://wanchap.com/"
languageCode = "en-us"
title = "Matt Wanchap"
theme = "hyde-hyde"

[params]
    authorimage = "matt.jpg"

[markup.goldmark.renderer]
    unsafe = true

[params.social]
    twitter = "MattWanchap"
    github = "mwanchap"
    facebook = "mwanchap"
    linkedin = "mwanchap"
    stackoverflow = "2939759"

[[menu.main]]
    name = "Projects"
    identifier = "portfolio"
    weight = 0
    url = "/portfolio/"
